#All options are case sensitive and must be terminated with a semicolon
TabletName="HUION Kamvas pro 13"; #Simple way to write what tablet the config is for
StripName="HUION Huion Monitor Touch Strip"; #Tablet's strip name
PadName="HUION Huion Monitor Pad"; #Tablet's pad name
PenName=""; #Tablet's pen name

#Keybinds (from top to bottom, leave as '0' to not bind anything)
PadNum=4; # Number of bindable pads
#evdev keybind numbers (0 disables the pad)
PadKeybinds=(0,0,29+44,29+31); #Extremely user unfriendly for now (Translating ASCII to evdev will stink)
StripUp=13; #=
StripDown=12; #-

#!!! Advanced config options (Default is for the kamvas pro 13) !!!
#evtest is great for finding these numbers
#Strip
StripTouched=15;
StripReleased=0;
StripTop=1;
StripBottom=6;

#Pads
PadIDs=(256,257,258,259);
PadPressed=1;
PadReleased=0;
#Pen
